-- 1) Tabla de modulos compartidos
create table if not exists public.modules (
  id bigint generated by default as identity primary key,
  name text not null,
  note text not null,
  url text not null,
  created_at timestamptz not null default now()
);

-- 2) Seguridad por filas
alter table public.modules enable row level security;

-- Lectura publica (alumnado sin login puede ver modulos)
drop policy if exists "modules_select_public" on public.modules;
create policy "modules_select_public"
on public.modules
for select
to anon, authenticated
using (true);

-- Escritura solo usuarios autenticados (profesorado)
drop policy if exists "modules_insert_auth" on public.modules;
create policy "modules_insert_auth"
on public.modules
for insert
to authenticated
with check (true);

drop policy if exists "modules_update_auth" on public.modules;
create policy "modules_update_auth"
on public.modules
for update
to authenticated
using (true)
with check (true);

drop policy if exists "modules_delete_auth" on public.modules;
create policy "modules_delete_auth"
on public.modules
for delete
to authenticated
using (true);
